/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aula_CI_VagnerFranca;

public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
//teste de workflow
